// apps/react_mfe/src/app/overview/react-features.tsx
import React from 'react';
import { NxCardXl } from '@components/cards/nx-card-xl';

import { api, performance, state, ui } from '@react_mfe/constants/icons';

const ReactFeatures: React.FC = () => {
  const features = [
    {
      icon: ui,
      title: 'Component Library',
      description: 'Reusable UI components built with React and styled with Tailwind CSS',
    },
    {
      icon: state,
      title: 'State Management',
      description: "Efficient state management patterns using React's Context API and hooks",
    },
    {
      icon: api,
      title: 'API Integration',
      description: 'Modern data fetching with React Query and custom hooks',
    },
    {
      icon: performance,
      title: 'Performance Optimized',
      description: 'Code splitting, lazy loading, and memoization for optimal performance',
    },
  ];
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
      {features.map((feature, index) => (
        <NxCardXl
          key={index}
          icon={feature.icon}
          title={feature.title}
          description={feature.description}
        />
      ))}
    </div>
  );
};

export default ReactFeatures;

// apps/vue_mfe/src/app/overview/vue-features.vue
<template>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
    <div
      v-for="(feature, index) in features"
      :key="index"
      class="border rounded p-4 shadow"
    >
      <div class="mb-2 text-2xl">{{ feature.icon }}</div>
      <h3 class="font-bold mb-1">{{ feature.title }}</h3>
      <p class="text-sm text-gray-600">{{ feature.description }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
const features = [
  {
    icon: '📦',
    title: 'Component Library',
    description: 'Reusable UI components built with Vue and styled with Tailwind CSS',
  },
  {
    icon: '⚙️',
    title: 'State Management',
    description: "Efficient state management using Vue's Composition API and Pinia",
  },
  {
    icon: '🔗',
    title: 'API Integration',
    description: 'Modern data fetching with Axios and custom composables',
  },
  {
    icon: '🚀',
    title: 'Performance Optimized',
    description: 'Code splitting, lazy loading, and memoization for optimal performance',
  },
];
</script>
